SELECT E.ID, CASE 
    WHEN PR <= 0.25 THEN 'LOW'
    WHEN PR <= 0.5 THEN 'MEDIUM'
    WHEN PR <= 0.75 THEN 'HIGH'
    ELSE 'CRITICAL'
    END AS COLONY_NAME
FROM ECOLI_DATA E LEFT JOIN 
(SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS PR
FROM ECOLI_DATA
) R ON E.ID = R.ID