-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) 'YEAR', MONTH(SALES_DATE) 'MONTH', GENDER 
, SALES_DATE, U.USER_ID
# , COUNT(*) 'USERS'
FROM ONLINE_SALE O LEFT JOIN USER_INFO U ON U.USER_ID = O.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER;

# SELECT * FROM USER_INFO;