SELECT ID, NAME, PLACES.HOST_ID
FROM PLACES JOIN (SELECT HOST_ID
                  FROM PLACES
                  GROUP BY HOST_ID
                  HAVING COUNT(ID) >= 2
) P2
ON PLACES.HOST_ID = P2.HOST_ID
ORDER BY ID;