SELECT CONCAT(CONCAT(CONCAT('/home/grep/src/', BEST.BOARD_ID), CONCAT('/', FILE_ID)), CONCAT(FILE_NAME, FILE_EXT)) AS FILE_PATH
FROM (
    SELECT BOARD_ID
    FROM (SELECT BOARD_ID
        FROM USED_GOODS_BOARD
        ORDER BY VIEWS DESC)
    WHERE ROWNUM <= 1
    ) BEST
JOIN USED_GOODS_FILE ON BEST.BOARD_ID = USED_GOODS_FILE.BOARD_ID
ORDER BY FILE_ID DESC