SELECT CATEGORY, MAX(PRICE) AS 'MAX_PRICE', 
       (SELECT PRODUCT_NAME FROM FOOD_PRODUCT WHERE PRICE = MAX(FP.PRICE) AND CATEGORY = FP.CATEGORY LIMIT 1) AS PRODUCT_NAME
FROM FOOD_PRODUCT FP
WHERE CATEGORY IN('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;
